version: "3.9"
services:
  product-service:
    build: ./backend/product-service
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - product-service
